apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /test-web
            backend:
              service:
                name: test-web-service
                port:
                  number: 8080
            pathType: Prefix