apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
  namespace: test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - image: drskyfox/test-web:1.0.5
          imagePullPolicy: Always
          name: kbe-test-web-service
          resources:
            limits:
              cpu: "300m"
              memory: "500Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://172.31.32.7/test
            - name: SPRING_RABBITMQ_VIRTUAL-HOST
              value: wallet-vhost
            - name: SPRING_RABBITMQ_HOST
              value: rmq-rabbitmq.broker.svc.cluster.local
            - name: SPRING_DATASOURCE_USERNAME
              value: test
            - name: SPRING_DATASOURCE_PASSWORD
              value: test
