apiVersion: v1
kind: Service
metadata:
  name: test-web
  namespace: test-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: test-web
  ports:
    - name: 8000-5000
      protocol: TCP
      port: 8080
      targetPort: 8080





