apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - image: drskyfox/test-web:1.0.3
          imagePullPolicy: Always
          name: kbe-test-web-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://10.0.0.10/ptest
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: E6_y66w18o6bh7LR
