apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: test-web
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 89.208.196.126
  selector:
    app: test-web
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080





