apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-testweb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-web
                port:
                  number: 8080


#    - host: echo1.example.com
#      http:
#        paths:
#          - backend:
#              service:
#                name: test-web
#                port:
#                  number: 80

