apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: test-web
spec:
  selector:
    app: test-web
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP




