apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-testweb
spec:
  rules:
    - host: echo1.example.com
      http:
        paths:
          - backend:
              service:
                name: test-web
                port:
                  number: 80

