apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - image: drskyfox/test-web:1.0.2
          imagePullPolicy: Always
          name: kbe-test-web-service
          ports:
            - containerPort: 8080
