apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-web
  name: test-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  strategy: {}
  template:
    metadata:
      labels:
        app: test-web
        visualize: "true"
    spec:
      containers:
        - image: drskyfox/test-web:1.0.1
          name: kbe-test-web-service
          ports:
            - containerPort: 8080
