kind: ConfigMap
apiVersion: v1
metadata:
  name: wallet-manager-config
  namespace: wallet
data:
  appsettings.json: |
    {
    "ConnectionStrings_": {
      "UserDbConnection": "User ID=walet;Password=walet22!;Host=172.31.32.7;Port=5432;Database=manager;Pooling=true;Connection Lifetime=0;"
    },
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    },
    "AllowedHosts": "*",
    "UserDbConnection": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=userDbManager;Pooling=true;Connection Lifetime=0;",
      "DbConnection__": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=web-api;Pooling=true;Connection Lifetime=0;"

    }


---


kind: ConfigMap
apiVersion: v1
metadata:
  name: wallet-m-main-config
  namespace: wallet
data:
  appsettings.json: |
    {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {SourceContext}{NewLine}\t{Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [
          "FromLogContext"
        ]
      },
      "AllowedHosts": "*",
      "DbConnection": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=web-api;Pooling=true;Connection Lifetime=0;",
      "UserDbConnection": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=userDbManager;Pooling=true;Connection Lifetime=0;",
      "ExtServices": [
        {
          "Key": "GooglePay",
          "Name": "GooglePay",
          "ManagementUrl": "https://g.mng.cl2.skyfactory.fun/Owners/Details/{businessId}"
        },
        {
          "Key": "ApplePass",
          "Name": "ApplePass",
          "ManagementUrl": "https://a.mng.cl2.skyfactory.fun/Owners/Details/{businessId}"
        }
      ]
    }
    
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wallet-m-apple-config
  namespace: wallet
data:
  appsettings.json: |
    {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Debug",
            "Microsoft.Hosting.Lifetime": "Information",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {SourceContext}{NewLine}\t{Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [
          "FromLogContext"
        ]
      },
      "AllowedHosts": "*",
      "DbConnection": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=web-api-apple;Pooling=true;Connection Lifetime=0;"
    }
    
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wallet-m-google-config
  namespace: wallet
data:
  appsettings.json: |
    {
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Debug",
            "Microsoft.Hosting.Lifetime": "Information",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level}] {SourceContext}{NewLine}\t{Message}{NewLine}{Exception}"
            }
          }
        ],
        "Enrich": [
          "FromLogContext"
        ]
      },
      "AllowedHosts": "*",
      "DbConnection": "User ID=wallet;Password=wallet22!;Host=172.31.32.7;Port=5432;Database=web-api-gpay;Pooling=true;Connection Lifetime=0;"
    }
    
    

