apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app.kubernetes.io/instance: wallet-api
    app.kubernetes.io/name: wallet-api
  name: wallet-api
  namespace: wallet
spec:
  tls:
    - hosts:
        - api.cloud.game-keeper.com
      secretName: api-cl-gk-com
  ingressClassName: nginx
  rules:
    - host: api.cloud.game-keeper.com
      http:
        paths:
          - backend:
              service:
                name: wallet-api
                port:
                  number: 9000
            path: /
            pathType: ImplementationSpecific
