apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
  namespace: wallet
spec:
  storageClassName: ebs-dynamic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi